[package]
name = "wesnoth_ai"
version = "0.1.0"
authors = ["Eli Dupree <vcs@elidupree.com>"]

[dependencies]
rand = "0.3"
serde_derive = "1.0"
serde_json = "1.0"
crossbeam = "0.2"
conrod = "0.55"

[dependencies.serde]
version = "1.0"
features = ["rc"]

[profile.dev]
opt-level = 3
