[package]
name = "wesnoth_ai"
version = "0.1.0"
authors = ["Eli Dupree <vcs@elidupree.com>"]

[dependencies]
rand = "0.3"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
crossbeam = "0.2"

[profile.dev]
opt-level = 3
