[package]
name = "wesnoth_ai"
version = "0.1.0"
authors = ["Eli Dupree <vcs@elidupree.com>"]

[dependencies]
rand = "0.3"
serde = "0.8"
serde_macros = "0.8"
serde_json = "0.8"

[profile.dev]
opt-level = 3
